version: '3.1'

services:
  local-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: where-i-go
      POSTGRES_USER: benoit
      POSTGRES_PASSWORD: local
    ports:
      - 5432:5432