services:
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=where-i-go
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
